# Generated by Django 4.0 on 2021-12-17 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiction_api', '0002_story_created_at_story_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='title',
            field=models.CharField(default='', max_length=128, unique=True),
        ),
    ]
